### PR TITLE
Fix OOB read crash in Pass16ScanMethodRefs

### PR DESCRIPTION
**Pull request by khang06**
I was running into a crash where Iced tried to disassemble past the end of the file, so here's a pretty straightforward fix for it.

### CODE REVIEW

**Comment by Kasuromi** [comment]
What is the game you got the out of bounds exception on? I've been unable to reproduce this on several games.

**Comment by khang06** [comment]
I ran into this on Rec Room. IIRC it also required modifying Cpp2IL to make it find CodeRegistration properly, which I did by porting [this.](https://github.com/khang06/Il2CppDumper-YuanShen/blob/master/Il2CppDumper/Program.cs#L243)

**Comment by ds5678** [comment]
Is this still an issue?

**Comment by khang06** [comment]
I'm not sure. The set up I used that ran into this issue is long gone at this point, so I can't really check if this still happens. Feel free to close this if you'd like.

**Pull request closed without merging**
