### PR TITLE
Create a non-generic Il2CppArrayBase class

### PR DESCRIPTION
**Pull request by ds5678**
This will be important for unstripping `ldlen`.

### CODE REVIEW

**Comment by ds5678** [comment]
Should `Il2CppArrayBase<T>.WrapNativeGenericArrayPointer(IntPtr)` become `Il2CppArrayBase.WrapNativeGenericArrayPointer<T>(IntPtr)`?

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1000

**Comment by ds5678** [comment]
> Should `Il2CppArrayBase<T>.WrapNativeGenericArrayPointer(IntPtr)` become `Il2CppArrayBase.WrapNativeGenericArrayPointer<T>(IntPtr)`?
> 
> https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1000

Now that I think about it some more, this should be a future pull request because it has implications on the generator, which I significantly changed in #124.

**Review by ManlyMarco — COMMENTED** [review]
Is Il2CppArrayBase or are classes inheriting it directly accessed by any plugin code? If yes, this looks like a binary compatibility break.

**Comment by ds5678** [comment]
> Is Il2CppArrayBase or are classes inheriting it directly accessed by any plugin code? If yes, this looks like a binary compatibility break.

Plugins can and do access these classes.

My pull request has two breaking changes:

* Moving `Length` to the base class
  * This is binary breaking but not source breaking.
  * The binary break can be avoided by adding a derived property that hides the base property.
* Changing `IsReadOnly` to an explicit interface implementation
  * This is a source and binary breaking change.
  * There is no reason for code to access this. It should have been this way from the start, but I can change it back if desired.

**Comment by ds5678** [comment]
I'm not sure how much breaking changes matter because my ultimate goal is to make lots of breaking changes. I want to do a proper C# type system with real interfaces and virtual methods. Porting to AsmResolver is just a first step towards that goal.

**Comment by ds5678** [comment]
> The binary break can be avoided by adding a derived property that hides the base property.

Done

**Review by Kasuromi — APPROVED** [review]

**Review by ManlyMarco — APPROVED** [review]

**Pull request merged**
